plugins {
    id 'io.micronaut.library' version '4.5.4'
    id 'maven-publish'
    id 'com.google.protobuf' version '0.9.5'
}

version getProperty('projectVersion')
group "coop.stlma.tech.protocolsn"

repositories {
    mavenCentral()
    mavenLocal()
}

micronaut {
    version = getProperty('micronautVersion')
}

dependencies {

    //web
    implementation("io.micronaut:micronaut-http-client")

    //reactor
    implementation("io.micronaut.reactor:micronaut-reactor")

    //security
    annotationProcessor("io.micronaut.security:micronaut-security-annotations")
    implementation("io.micronaut.security:micronaut-security-oauth2")
    implementation("io.micronaut.security:micronaut-security-jwt")

    //grpc
    implementation("io.grpc:grpc-protobuf:${grpcVersion}")
    implementation("io.grpc:grpc-services:${grpcVersion}")
    implementation("io.grpc:grpc-stub:${grpcVersion}")
    implementation("io.micronaut.grpc:micronaut-grpc-client-runtime")
    implementation("io.micronaut.grpc:micronaut-grpc-server-runtime")
    implementation("com.google.protobuf:protobuf-java-util:${protobufVersion}")

    implementation("coop.stlma.tech.protocolsn:common-lib:0.5.1")

    //lombok
    annotationProcessor("org.projectlombok:lombok")
    compileOnly("org.projectlombok:lombok")
}

protobuf {
    protoc { artifact = "com.google.protobuf:protoc:${protocVersion}" }
    plugins {
        grpc { artifact = "io.grpc:protoc-gen-grpc-java:${grpcVersion}" }
    }

    generateProtoTasks {
        all()*.plugins {
            grpc {
                option '@generated=omit'
            }
        }
    }
}

// use JUnit 5 platform
test {
    useJUnitPlatform()
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = project.group
            artifactId = "plugin-lib-api"
            version = project.version

            from components.java
        }
    }
}