package coop.stlma.tech.protocolsn.pluginlib.registration.domain;


import io.micronaut.core.annotation.Introspected;
import io.micronaut.serde.annotation.Serdeable;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.UUID;

/**
 * Domain object representing a registered plugin
 *
 * @author John Meyerin
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Introspected
@Serdeable
public class PluginRegistration {

    /**
     * Autogenerated UUID serving as the primary key.
     */
    private UUID id;
    /**
     * Distinguishing name for the plugin
     */
    private String pluginName;
    /**
     * Host URL of the plugin
     */
    private String pluginLocation;
}
